config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'comparison_reports#index'

  resources :scan_reports, only: %i[create]
  resources :comparison_reports, only: %i[index new create show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comparison_report.rb
# frozen_string_literal: true

class ComparisonReport < ApplicationRecord
  belongs_to :scan_report
  has_many :results, class_name: 'ComparisonResult', dependent: :destroy

  def generate(comparison_records)
    return unless scan_report

    comparison_records.each do |record|
      related_scan = scan_result(record['LOCATION'])
      results.build(comparison_result_attributes(record, related_scan))
    end

    save
  end

  def discrepancies
    results.where('cardinality(discrepancies) > 0')
  end

  def non_discrepancies
    results.where('cardinality(discrepancies) = 0')
  end

  private

  def scan_result(location_name)
    scan_report.results.find_by(name: location_name)
  end

  def comparison_result_attributes(comparison_record, related_scan)
    {
      name: comparison_record['LOCATION'],
      expected_barcodes: [comparison_record['ITEM']].compact,
      detected_barcodes: related_scan&.detected_barcodes,
      discrepancies: discrepancies_xor(related_scan&.detected_barcodes, [comparison_record['ITEM']]),
      report: self
    }
  end

  def discrepancies_xor(detected, expected)
    return [] if detected.nil?

    xor = (detected - expected) + (expected - detected)
    xor.compact_blank
  end
end

app/models/comparison_result.rb
# frozen_string_literal: true

class ComparisonResult < ApplicationRecord
  belongs_to :report, class_name: 'ComparisonReport', foreign_key: 'comparison_report_id', inverse_of: :results

  def status
    if expected_barcodes.present?
      return :empty_unexpected if detected_barcodes.blank?

      expected_barcodes == detected_barcodes ? :occupied_expected : :occupied_incorrect
    else
      detected_barcodes.present? ? :occupied_unexpected : :empty_expected
    end
  end
end

app/models/scan_report.rb
# frozen_string_literal: true

class ScanReport < ApplicationRecord
  has_many :results, class_name: 'ScanResult', dependent: :destroy
  has_many :comparison_reports, dependent: :destroy
end

app/models/scan_result.rb
# frozen_string_literal: true

class ScanResult < ApplicationRecord
  belongs_to :report, class_name: 'ScanReport', foreign_key: 'scan_report_id', inverse_of: :results
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comparison_reports_controller.rb
# frozen_string_literal: true

require 'csv'

class ComparisonReportsController < ApplicationController
  def index
    @reports = ComparisonReport.all
  end

  def show
    @report = ComparisonReport.find(params[:id])
  end

  def new
    @report = ComparisonReport.new
  end

  def create
    @report = ComparisonReport.new(comparison_report_params)
    if @report.generate(comparison_input_data)
      redirect_to comparison_report_path(@report)
    else
      render :new
    end
  end

  private

  def comparison_report_params
    params.require(:comparison_report).permit(:scan_report_id)
  end

  def comparison_input_data
    CSV.parse(params[:comparison_report][:comparison_file].tempfile, headers: true).map(&:to_h)
  end
end

app/controllers/scan_reports_controller.rb
# frozen_string_literal: true

class ScanReportsController < ActionController::API
  def create
    report = ScanReport.create
    results = report.results.create(JSON.parse(request.body.read))
    render json: { results_imported: results.count }
  rescue JSON::ParserError => e
    render json: { error: e.message }, status: :bad_request
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/comparison_reports/_comparison_results_table.erb
<table class="table mb-12" id="<%= id %>-table">
  <thead>
    <tr>
      <th>Location Name</th>
      <th>Expected Barcodes</th>
      <th>Detected Barcodes</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% comparison_results.each do |comparison_result| %>
      <tr id="result-<%= comparison_result.id %>">
        <td><%= comparison_result.name %></td>
        <td><%= comparison_result.expected_barcodes.join %></td>
        <td><%= comparison_result.detected_barcodes.join %></td>
        <td class=<%= status_class %>><%= t(comparison_result.status, scope: "comparison_reports.show") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comparison_reports/index.erb
<div class="container flex items-baseline justify-between w-100">
  <h1 class="text-4xl">Comparison Reports</h1>
  <%= link_to 'New Comparison', new_comparison_report_path, class: "btn" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Created By</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td>Alice Bob</td>
        <td><%= report.created_at %></td>
        <td><%= link_to "👀", report, class: "btn btn-sm btn-primary" %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comparison_reports/new.erb
<div class="container">
<div class="container flex items-baseline justify-between w-100">
  <h1 class="text-4xl">New Comparison</h1>
  <%= link_to 'Back', comparison_reports_path, class: "btn" %>
</div>

  <%= form_with model: @report, data: { turbo: false }, class: "form-control" do |form| %>
    <%= form.label :scan_report_id, "Select a scan report to compare", class: "label-text" %>

    <div class="container flex mb-4">
      <%= form.collection_radio_buttons :scan_report_id, ScanReport.order(created_at: :desc), :id, :created_at, {}, {class: "radio radio-primary mx-3" }%>
    </div>

    <%= form.label :comparison_file, "Upload a file to compare the scan to", class: "label-text" %>
    <%= form.file_field :comparison_file, class: "mb-4" %>

    <%= form.submit "Generate", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/comparison_reports/show.erb
<div class="container flex items-baseline justify-between w-100">
  <h1 class="text-4xl">Comparison Report#<%=@report.id%></h1>
  <%= link_to 'Back', comparison_reports_path, class: "btn" %>
</div>

<h2 class="text-2xl">Discrepancies (<%= @report.discrepancies.count %> records)</h1>
<%= render "comparison_results_table", comparison_results: @report.discrepancies, id: "discrepancy", status_class: "bg-error/30" %>

<h2 class="text-2xl">Other Results (<%= @report.non_discrepancies.count %> records)</h1>
<%= render "comparison_results_table", comparison_results: @report.non_discrepancies, id: "other", status_class: "bg-success/40" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DexoryExercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>